### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [andihoerudin24/aplikasi-pendaftaran-pasien#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by andihoerudin24** [comment]
Thank you, Please design. I am very grateful and very happy if you design

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? if yes tell me which one do you like. and if there have any changes, don't hesitate to tell me.
![sistem pendaftaran pasien](https://user-images.githubusercontent.com/33461607/45507257-bea43500-b7bb-11e8-8613-f37965802b78.png)

**Comment by andihoerudin24** [comment]
I like number 8. Can you make a web display. If you can make a web page view, we can build an application with you, my display section, which processes the data

**Comment by mansya** [comment]
I will see the appearance of your wab as soon as possible.

**Comment by mansya** [comment]
why did you close this conversation? do you not want me to continue?

**Comment by andihoerudin24** [comment]
If you're willing. I will make a new application, we develop it together.
You are the part of the display that I process it if you want

**Comment by andihoerudin24** [comment]
If you're willing. I will make a new application, we develop it together. You are the part of the display that I process it if you want

**Comment by mansya** [comment]
I like it very much. Let's do it

**Comment by andihoerudin24** [comment]
Good. Later that night I will make a new repo. You want an application
about what is really needed
